package com.github.WhiteMagic2014.gptApi.Images.pojo;

/**
 * Represents the url or the content of an image generated by the OpenAI API.
 * https://platform.openai.com/docs/api-reference/images/object
 */
public class OpenAiImage {

    String b64_json;

    String url;

    String revised_prompt;

    public String getB64_json() {
        return b64_json;
    }

    public void setB64_json(String b64_json) {
        this.b64_json = b64_json;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getRevised_prompt() {
        return revised_prompt;
    }

    public void setRevised_prompt(String revised_prompt) {
        this.revised_prompt = revised_prompt;
    }

    @Override
    public String toString() {
        return "OpenAiImage{" +
                "b64_json='" + b64_json + '\'' +
                ", url='" + url + '\'' +
                ", revised_prompt='" + revised_prompt + '\'' +
                '}';
    }
}
