package com.github.WhiteMagic2014.gptApi.Chat.pojo;

import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.serializer.SerializerFeature;

/**
 * For more detailed information on function calling, please refer to https://platform.openai.com/docs/guides/gpt/function-calling
 *
 * @Description: CreateChatCompletionRequest message
 * @author: magic chen
 * @date: 2023/3/2 10:41
 **/
public class ChatMessage {


    /**
     * The role of the messages author. One of system, user, assistant, or function.
     */
    private String role;

    /**
     * The contents of the message. content is required for all messages except assistant messages with function calls.
     */
    @JSONField(serialzeFeatures = SerializerFeature.WriteMapNullValue)
    private String content;

    /**
     * The name of the author of this message.
     * name is required if role is function, and it should be the name of the function whose response is in the content.
     * May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
     */
    private String name;

    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    private JSONObject function_call;


    public static ChatMessage systemMessage(String content) {
        return new ChatMessage("system", content);
    }

    public static ChatMessage userMessage(String content) {
        return new ChatMessage("user", content);
    }

    public static ChatMessage assistantMessage(String content) {
        return new ChatMessage("assistant", content);
    }

    public static ChatMessage functionMessage(String name, String content) {
        ChatMessage tmp = new ChatMessage("function", content);
        tmp.setName(name);
        return tmp;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public JSONObject getFunction_call() {
        return function_call;
    }

    public void setFunction_call(JSONObject function_call) {
        this.function_call = function_call;
    }

    public ChatMessage() {
    }

    public ChatMessage(String role, String content) {
        this.role = role;
        this.content = content;
    }

    @Override
    public String toString() {
        return "ChatMessage{" +
                "role='" + role + '\'' +
                ", content='" + content + '\'' +
                ", name='" + name + '\'' +
                ", function_call=" + function_call +
                '}';
    }
}
